#!/usr/bin/env bash

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

echo 'Install zsh'
echo '------------'
sudo apt-get install -y zsh

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
chsh -s `which zsh`

echo 'Create symlinks'
echo '------------'

# Add global gitignore and setup editor
rm $HOME/.global-gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile "$HOME/.global-gitignore"
git config --global include.path "$HOME/.dotfiles/config/.gitconfig"

git config --global core.editor "vim"

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Symlink vim prefs
rm $HOME/.vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc
rm $HOME/.vim
ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim

# Activate z
cd ~/.dotfiles/shell
chmod +x z.sh
rm -f $HOME/.z
ln -s $HOME/.dotfiles/shell/z.sh $HOME/.z

sudo apt-get update

echo 'Install wget'
echo '------------'
sudo apt-get install -y wget

echo 'Install httpie'
echo '--------------'
sudo apt-get install -y httpie

echo 'Install ncdu'
echo '------------'
sudo apt-get install -y ncdu

echo 'Install ack'
echo '-----------'
sudo apt-get install -y ack

echo 'Install tldr'
echo '-----------'
sudo apt-get install -y tldr

echo 'Install vim'
echo '-----------'
sudo apt-get install -y vim

echo 'Install zsh-autosuggestions'
echo '---------------------------'
# from https://software.opensuse.org/download.html?project=shells%3Azsh-users%3Azsh-autosuggestions&package=zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

echo 'Install irak/prestissimo'
echo '---------------------------------'
composer global require hirak/prestissimo # need to be installed via composer directly

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo 'Things to do to make the agnoster terminal theme work:'
echo '1. Install menlo patched font included in ~/.dotfiles/misc https://gist.github.com/qrush/1595572/raw/Menlo-Powerline.otf'
echo '2. Install patched solarized theme included in ~/.dotfiles/misc'
echo '3. Allow sudo permittance with fingerprint. Futher instructions in ~/.dotfiles/misc/fingerprint.sh'

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'