#!/usr/bin/env bash

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

echo 'Install zsh'
echo '------------'
sudo apt-get install -y zsh

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
chsh -s `which zsh`

echo 'Install zsh theme remy'
echo '------------'
ln -s $HOME/.dotfiles/zshrc/remy.zsh-theme $HOME/.oh-my-zsh/custom/themes/remy.zsh-theme

echo 'Installing zsh plugins'
echo '------------'
git clone https://github.com/jessarcher/zsh-artisan.git ~/.oh-my-zsh/custom/plugins/artisan

echo 'Create symlinks'
echo '------------'

# Add global gitignore and setup editor
rm $HOME/.global-gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile "$HOME/.global-gitignore"
git config --global include.path "$HOME/.dotfiles/config/.gitconfig"

git config --global core.editor "vim"

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Symlink vim prefs
rm $HOME/.vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc
rm $HOME/.vim
ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim

# Activate z
cd ~/.dotfiles/shell
rm -f $HOME/.z
ln -s $HOME/.dotfiles/shell/z.sh $HOME/.z

sudo apt-get update

echo 'Install wget'
echo '------------'
sudo apt-get install -y wget

echo 'Install httpie'
echo '--------------'
sudo apt-get install -y httpie

echo 'Install ncdu'
echo '------------'
sudo apt-get install -y ncdu

echo 'Install ack'
echo '-----------'
sudo apt-get install -y ack

echo 'Install tldr'
echo '-----------'
sudo apt-get install -y tldr

echo 'Install vim'
echo '-----------'
sudo apt-get install -y vim

echo 'Install nmap'
echo '-----------'
sudo apt-get install -y nmap

echo 'Install prettyping'
echo '---------------------------'
sudo apt-get install prettyping -y

echo 'Install fzf'
echo '-----------'
linuxDistr=$(awk -F= '/^ID=/{print $2}' /etc/os-release)
if [ "$linuxDistr" == "debian" ] || [ "$linuxDistr" == "rasbian" ]; then
    sudo apt-get install fzf
else
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install
fi

echo 'Install zsh-autosuggestions'
echo '---------------------------'
# from https://software.opensuse.org/download.html?project=shells%3Azsh-users%3Azsh-autosuggestions&package=zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

if which composer >/dev/null; then
    echo 'Install irak/prestissimo'
    echo '---------------------------------'
    composer global require hirak/prestissimo # need to be installed via composer directly
fi

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'